{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='testSuiteExecution', url='', help='"TestSuiteExecution is the Schema for the testsuiteexecutions API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of TestSuiteExecution', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'tests.testkube.io/v1',
    kind: 'TestSuiteExecution',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"TestSuiteExecutionSpec defines the desired state of TestSuiteExecution"'),
  spec: {
    '#executionRequest':: d.obj(help='"test suite execution request body"'),
    executionRequest: {
      '#contentRequest':: d.obj(help='"test content request body"'),
      contentRequest: {
        '#repository':: d.obj(help='"repository parameters for tests in git repositories"'),
        repository: {
          '#withBranch':: d.fn(help='"branch/tag name for checkout"', args=[d.arg(name='branch', type=d.T.string)]),
          withBranch(branch): { spec+: { executionRequest+: { contentRequest+: { repository+: { branch: branch } } } } },
          '#withCommit':: d.fn(help='"commit id (sha) for checkout"', args=[d.arg(name='commit', type=d.T.string)]),
          withCommit(commit): { spec+: { executionRequest+: { contentRequest+: { repository+: { commit: commit } } } } },
          '#withPath':: d.fn(help='"if needed we can checkout particular path (dir or file) in case of BIG/mono repositories"', args=[d.arg(name='path', type=d.T.string)]),
          withPath(path): { spec+: { executionRequest+: { contentRequest+: { repository+: { path: path } } } } },
          '#withWorkingDir':: d.fn(help='"if provided we checkout the whole repository and run test from this directory"', args=[d.arg(name='workingDir', type=d.T.string)]),
          withWorkingDir(workingDir): { spec+: { executionRequest+: { contentRequest+: { repository+: { workingDir: workingDir } } } } },
        },
      },
      '#runningContext':: d.obj(help='"running context for test or test suite execution"'),
      runningContext: {
        '#withContext':: d.fn(help='"Context value depending from its type"', args=[d.arg(name='context', type=d.T.string)]),
        withContext(context): { spec+: { executionRequest+: { runningContext+: { context: context } } } },
        '#withType':: d.fn(help='"One of possible context types"', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { executionRequest+: { runningContext+: { type: type } } } },
      },
      '#withConcurrencyLevel':: d.fn(help='"number of tests run in parallel"', args=[d.arg(name='concurrencyLevel', type=d.T.integer)]),
      withConcurrencyLevel(concurrencyLevel): { spec+: { executionRequest+: { concurrencyLevel: concurrencyLevel } } },
      '#withCronJobTemplate':: d.fn(help='"cron job template extensions"', args=[d.arg(name='cronJobTemplate', type=d.T.string)]),
      withCronJobTemplate(cronJobTemplate): { spec+: { executionRequest+: { cronJobTemplate: cronJobTemplate } } },
      '#withExecutionLabels':: d.fn(help='"execution labels"', args=[d.arg(name='executionLabels', type=d.T.object)]),
      withExecutionLabels(executionLabels): { spec+: { executionRequest+: { executionLabels: executionLabels } } },
      '#withExecutionLabelsMixin':: d.fn(help='"execution labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='executionLabels', type=d.T.object)]),
      withExecutionLabelsMixin(executionLabels): { spec+: { executionRequest+: { executionLabels+: executionLabels } } },
      '#withHttpProxy':: d.fn(help='"http proxy for executor containers"', args=[d.arg(name='httpProxy', type=d.T.string)]),
      withHttpProxy(httpProxy): { spec+: { executionRequest+: { httpProxy: httpProxy } } },
      '#withHttpsProxy':: d.fn(help='"https proxy for executor containers"', args=[d.arg(name='httpsProxy', type=d.T.string)]),
      withHttpsProxy(httpsProxy): { spec+: { executionRequest+: { httpsProxy: httpsProxy } } },
      '#withLabels':: d.fn(help='"test suite labels"', args=[d.arg(name='labels', type=d.T.object)]),
      withLabels(labels): { spec+: { executionRequest+: { labels: labels } } },
      '#withLabelsMixin':: d.fn(help='"test suite labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
      withLabelsMixin(labels): { spec+: { executionRequest+: { labels+: labels } } },
      '#withName':: d.fn(help='"test execution custom name"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { executionRequest+: { name: name } } },
      '#withNamespace':: d.fn(help='"test kubernetes namespace (\\\\\\"testkube\\\\\\" when not set)"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { executionRequest+: { namespace: namespace } } },
      '#withNumber':: d.fn(help='"test suite execution number"', args=[d.arg(name='number', type=d.T.integer)]),
      withNumber(number): { spec+: { executionRequest+: { number: number } } },
      '#withSecretUUID':: d.fn(help='"secret uuid"', args=[d.arg(name='secretUUID', type=d.T.string)]),
      withSecretUUID(secretUUID): { spec+: { executionRequest+: { secretUUID: secretUUID } } },
      '#withSync':: d.fn(help='"whether to start execution sync or async"', args=[d.arg(name='sync', type=d.T.boolean)]),
      withSync(sync): { spec+: { executionRequest+: { sync: sync } } },
      '#withTestSuiteExecutionName':: d.fn(help='"test suite execution name started the test suite execution"', args=[d.arg(name='testSuiteExecutionName', type=d.T.string)]),
      withTestSuiteExecutionName(testSuiteExecutionName): { spec+: { executionRequest+: { testSuiteExecutionName: testSuiteExecutionName } } },
      '#withTimeout':: d.fn(help='"duration in seconds the test suite may be active, until its stopped"', args=[d.arg(name='timeout', type=d.T.integer)]),
      withTimeout(timeout): { spec+: { executionRequest+: { timeout: timeout } } },
      '#withVariables':: d.fn(help='', args=[d.arg(name='variables', type=d.T.object)]),
      withVariables(variables): { spec+: { executionRequest+: { variables: variables } } },
      '#withVariablesMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='variables', type=d.T.object)]),
      withVariablesMixin(variables): { spec+: { executionRequest+: { variables+: variables } } },
    },
    '#testSuite':: d.obj(help=''),
    testSuite: {
      '#withName':: d.fn(help='"object name"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { testSuite+: { name: name } } },
      '#withNamespace':: d.fn(help='"object kubernetes namespace"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { testSuite+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
