{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='test', url='', help='"Test is the Schema for the tests API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Test', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'tests.testkube.io/v3',
    kind: 'Test',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"TestSpec defines the desired state of Test"'),
  spec: {
    '#content':: d.obj(help='"test content object"'),
    content: {
      '#repository':: d.obj(help='"repository of test content"'),
      repository: {
        '#tokenSecret':: d.obj(help='"SecretRef is the Testkube internal reference for secret storage in Kubernetes secrets"'),
        tokenSecret: {
          '#withKey':: d.fn(help='"object key"', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { spec+: { content+: { repository+: { tokenSecret+: { key: key } } } } },
          '#withName':: d.fn(help='"object name"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { content+: { repository+: { tokenSecret+: { name: name } } } } },
        },
        '#usernameSecret':: d.obj(help='"SecretRef is the Testkube internal reference for secret storage in Kubernetes secrets"'),
        usernameSecret: {
          '#withKey':: d.fn(help='"object key"', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { spec+: { content+: { repository+: { usernameSecret+: { key: key } } } } },
          '#withName':: d.fn(help='"object name"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { content+: { repository+: { usernameSecret+: { name: name } } } } },
        },
        '#withAuthType':: d.fn(help='"auth type for git requests"', args=[d.arg(name='authType', type=d.T.string)]),
        withAuthType(authType): { spec+: { content+: { repository+: { authType: authType } } } },
        '#withBranch':: d.fn(help='"branch/tag name for checkout"', args=[d.arg(name='branch', type=d.T.string)]),
        withBranch(branch): { spec+: { content+: { repository+: { branch: branch } } } },
        '#withCertificateSecret':: d.fn(help='"git auth certificate secret for private repositories"', args=[d.arg(name='certificateSecret', type=d.T.string)]),
        withCertificateSecret(certificateSecret): { spec+: { content+: { repository+: { certificateSecret: certificateSecret } } } },
        '#withCommit':: d.fn(help='"commit id (sha) for checkout"', args=[d.arg(name='commit', type=d.T.string)]),
        withCommit(commit): { spec+: { content+: { repository+: { commit: commit } } } },
        '#withPath':: d.fn(help='"if needed we can checkout particular path (dir or file) in case of BIG/mono repositories"', args=[d.arg(name='path', type=d.T.string)]),
        withPath(path): { spec+: { content+: { repository+: { path: path } } } },
        '#withType':: d.fn(help='"VCS repository type"', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { content+: { repository+: { type: type } } } },
        '#withUri':: d.fn(help='"uri of content file or git directory"', args=[d.arg(name='uri', type=d.T.string)]),
        withUri(uri): { spec+: { content+: { repository+: { uri: uri } } } },
        '#withWorkingDir':: d.fn(help='"if provided we checkout the whole repository and run test from this directory"', args=[d.arg(name='workingDir', type=d.T.string)]),
        withWorkingDir(workingDir): { spec+: { content+: { repository+: { workingDir: workingDir } } } },
      },
      '#withData':: d.fn(help='"test content body"', args=[d.arg(name='data', type=d.T.string)]),
      withData(data): { spec+: { content+: { data: data } } },
      '#withType':: d.fn(help='"test type"', args=[d.arg(name='type', type=d.T.string)]),
      withType(type): { spec+: { content+: { type: type } } },
      '#withUri':: d.fn(help='"uri of test content"', args=[d.arg(name='uri', type=d.T.string)]),
      withUri(uri): { spec+: { content+: { uri: uri } } },
    },
    '#executionRequest':: d.obj(help='"test execution request body"'),
    executionRequest: {
      '#artifactRequest':: d.obj(help='"artifact request body with test artifacts"'),
      artifactRequest: {
        '#withDirs':: d.fn(help='"artifact directories for scraping"', args=[d.arg(name='dirs', type=d.T.array)]),
        withDirs(dirs): { spec+: { executionRequest+: { artifactRequest+: { dirs: if std.isArray(v=dirs) then dirs else [dirs] } } } },
        '#withDirsMixin':: d.fn(help='"artifact directories for scraping"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='dirs', type=d.T.array)]),
        withDirsMixin(dirs): { spec+: { executionRequest+: { artifactRequest+: { dirs+: if std.isArray(v=dirs) then dirs else [dirs] } } } },
        '#withMasks':: d.fn(help='"regexp to filter scraped artifacts, single or comma separated"', args=[d.arg(name='masks', type=d.T.array)]),
        withMasks(masks): { spec+: { executionRequest+: { artifactRequest+: { masks: if std.isArray(v=masks) then masks else [masks] } } } },
        '#withMasksMixin':: d.fn(help='"regexp to filter scraped artifacts, single or comma separated"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='masks', type=d.T.array)]),
        withMasksMixin(masks): { spec+: { executionRequest+: { artifactRequest+: { masks+: if std.isArray(v=masks) then masks else [masks] } } } },
        '#withOmitFolderPerExecution':: d.fn(help="\"don't use a separate folder for execution artifacts\"", args=[d.arg(name='omitFolderPerExecution', type=d.T.boolean)]),
        withOmitFolderPerExecution(omitFolderPerExecution): { spec+: { executionRequest+: { artifactRequest+: { omitFolderPerExecution: omitFolderPerExecution } } } },
        '#withSharedBetweenPods':: d.fn(help='"whether to share volume between pods"', args=[d.arg(name='sharedBetweenPods', type=d.T.boolean)]),
        withSharedBetweenPods(sharedBetweenPods): { spec+: { executionRequest+: { artifactRequest+: { sharedBetweenPods: sharedBetweenPods } } } },
        '#withStorageBucket':: d.fn(help='"artifact bucket storage"', args=[d.arg(name='storageBucket', type=d.T.string)]),
        withStorageBucket(storageBucket): { spec+: { executionRequest+: { artifactRequest+: { storageBucket: storageBucket } } } },
        '#withStorageClassName':: d.fn(help='"artifact storage class name for container executor"', args=[d.arg(name='storageClassName', type=d.T.string)]),
        withStorageClassName(storageClassName): { spec+: { executionRequest+: { artifactRequest+: { storageClassName: storageClassName } } } },
        '#withVolumeMountPath':: d.fn(help='"artifact volume mount path for container executor"', args=[d.arg(name='volumeMountPath', type=d.T.string)]),
        withVolumeMountPath(volumeMountPath): { spec+: { executionRequest+: { artifactRequest+: { volumeMountPath: volumeMountPath } } } },
      },
      '#envConfigMaps':: d.obj(help='"config map references"'),
      envConfigMaps: {
        '#reference':: d.obj(help='"LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace."'),
        reference: {
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { reference+: { name: name } },
        },
        '#withMapToVariables':: d.fn(help='"whether we shoud map to variables from resource"', args=[d.arg(name='mapToVariables', type=d.T.boolean)]),
        withMapToVariables(mapToVariables): { mapToVariables: mapToVariables },
        '#withMount':: d.fn(help='"whether we shoud mount resource"', args=[d.arg(name='mount', type=d.T.boolean)]),
        withMount(mount): { mount: mount },
        '#withMountPath':: d.fn(help='"where we shoud mount resource"', args=[d.arg(name='mountPath', type=d.T.string)]),
        withMountPath(mountPath): { mountPath: mountPath },
      },
      '#envSecrets':: d.obj(help='"secret references"'),
      envSecrets: {
        '#reference':: d.obj(help='"LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace."'),
        reference: {
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { reference+: { name: name } },
        },
        '#withMapToVariables':: d.fn(help='"whether we shoud map to variables from resource"', args=[d.arg(name='mapToVariables', type=d.T.boolean)]),
        withMapToVariables(mapToVariables): { mapToVariables: mapToVariables },
        '#withMount':: d.fn(help='"whether we shoud mount resource"', args=[d.arg(name='mount', type=d.T.boolean)]),
        withMount(mount): { mount: mount },
        '#withMountPath':: d.fn(help='"where we shoud mount resource"', args=[d.arg(name='mountPath', type=d.T.string)]),
        withMountPath(mountPath): { mountPath: mountPath },
      },
      '#imagePullSecrets':: d.obj(help='"container executor image pull secrets"'),
      imagePullSecrets: {
        '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
      },
      '#slavePodRequest':: d.obj(help='"pod request body"'),
      slavePodRequest: {
        '#resources':: d.obj(help='"pod resources request specification"'),
        resources: {
          '#limits':: d.obj(help='"resource request specification"'),
          limits: {
            '#withCpu':: d.fn(help='"requested cpu units"', args=[d.arg(name='cpu', type=d.T.string)]),
            withCpu(cpu): { spec+: { executionRequest+: { slavePodRequest+: { resources+: { limits+: { cpu: cpu } } } } } },
            '#withMemory':: d.fn(help='"requested memory units"', args=[d.arg(name='memory', type=d.T.string)]),
            withMemory(memory): { spec+: { executionRequest+: { slavePodRequest+: { resources+: { limits+: { memory: memory } } } } } },
          },
          '#requests':: d.obj(help='"resource request specification"'),
          requests: {
            '#withCpu':: d.fn(help='"requested cpu units"', args=[d.arg(name='cpu', type=d.T.string)]),
            withCpu(cpu): { spec+: { executionRequest+: { slavePodRequest+: { resources+: { requests+: { cpu: cpu } } } } } },
            '#withMemory':: d.fn(help='"requested memory units"', args=[d.arg(name='memory', type=d.T.string)]),
            withMemory(memory): { spec+: { executionRequest+: { slavePodRequest+: { resources+: { requests+: { memory: memory } } } } } },
          },
        },
        '#withPodTemplate':: d.fn(help='"pod template extensions"', args=[d.arg(name='podTemplate', type=d.T.string)]),
        withPodTemplate(podTemplate): { spec+: { executionRequest+: { slavePodRequest+: { podTemplate: podTemplate } } } },
        '#withPodTemplateReference':: d.fn(help='"name of the template resource"', args=[d.arg(name='podTemplateReference', type=d.T.string)]),
        withPodTemplateReference(podTemplateReference): { spec+: { executionRequest+: { slavePodRequest+: { podTemplateReference: podTemplateReference } } } },
      },
      '#withActiveDeadlineSeconds':: d.fn(help='"Optional duration in seconds the pod may be active on the node relative to StartTime before the system will actively try to mark it failed and kill associated containers. Value must be a positive integer."', args=[d.arg(name='activeDeadlineSeconds', type=d.T.integer)]),
      withActiveDeadlineSeconds(activeDeadlineSeconds): { spec+: { executionRequest+: { activeDeadlineSeconds: activeDeadlineSeconds } } },
      '#withArgs':: d.fn(help='"additional executor binary arguments"', args=[d.arg(name='args', type=d.T.array)]),
      withArgs(args): { spec+: { executionRequest+: { args: if std.isArray(v=args) then args else [args] } } },
      '#withArgsMixin':: d.fn(help='"additional executor binary arguments"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='args', type=d.T.array)]),
      withArgsMixin(args): { spec+: { executionRequest+: { args+: if std.isArray(v=args) then args else [args] } } },
      '#withArgsMode':: d.fn(help='"usage mode for arguments"', args=[d.arg(name='argsMode', type=d.T.string)]),
      withArgsMode(argsMode): { spec+: { executionRequest+: { argsMode: argsMode } } },
      '#withCommand':: d.fn(help='"executor binary command"', args=[d.arg(name='command', type=d.T.array)]),
      withCommand(command): { spec+: { executionRequest+: { command: if std.isArray(v=command) then command else [command] } } },
      '#withCommandMixin':: d.fn(help='"executor binary command"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='command', type=d.T.array)]),
      withCommandMixin(command): { spec+: { executionRequest+: { command+: if std.isArray(v=command) then command else [command] } } },
      '#withCronJobTemplate':: d.fn(help='"cron job template extensions"', args=[d.arg(name='cronJobTemplate', type=d.T.string)]),
      withCronJobTemplate(cronJobTemplate): { spec+: { executionRequest+: { cronJobTemplate: cronJobTemplate } } },
      '#withCronJobTemplateReference':: d.fn(help='"name of the template resource"', args=[d.arg(name='cronJobTemplateReference', type=d.T.string)]),
      withCronJobTemplateReference(cronJobTemplateReference): { spec+: { executionRequest+: { cronJobTemplateReference: cronJobTemplateReference } } },
      '#withEnvConfigMaps':: d.fn(help='"config map references"', args=[d.arg(name='envConfigMaps', type=d.T.array)]),
      withEnvConfigMaps(envConfigMaps): { spec+: { executionRequest+: { envConfigMaps: if std.isArray(v=envConfigMaps) then envConfigMaps else [envConfigMaps] } } },
      '#withEnvConfigMapsMixin':: d.fn(help='"config map references"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='envConfigMaps', type=d.T.array)]),
      withEnvConfigMapsMixin(envConfigMaps): { spec+: { executionRequest+: { envConfigMaps+: if std.isArray(v=envConfigMaps) then envConfigMaps else [envConfigMaps] } } },
      '#withEnvSecrets':: d.fn(help='"secret references"', args=[d.arg(name='envSecrets', type=d.T.array)]),
      withEnvSecrets(envSecrets): { spec+: { executionRequest+: { envSecrets: if std.isArray(v=envSecrets) then envSecrets else [envSecrets] } } },
      '#withEnvSecretsMixin':: d.fn(help='"secret references"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='envSecrets', type=d.T.array)]),
      withEnvSecretsMixin(envSecrets): { spec+: { executionRequest+: { envSecrets+: if std.isArray(v=envSecrets) then envSecrets else [envSecrets] } } },
      '#withEnvs':: d.fn(help='"Environment variables passed to executor. Deprecated: use Basic Variables instead"', args=[d.arg(name='envs', type=d.T.object)]),
      withEnvs(envs): { spec+: { executionRequest+: { envs: envs } } },
      '#withEnvsMixin':: d.fn(help='"Environment variables passed to executor. Deprecated: use Basic Variables instead"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='envs', type=d.T.object)]),
      withEnvsMixin(envs): { spec+: { executionRequest+: { envs+: envs } } },
      '#withExecutePostRunScriptBeforeScraping':: d.fn(help='"execute post run script before scraping (prebuilt executor only)"', args=[d.arg(name='executePostRunScriptBeforeScraping', type=d.T.boolean)]),
      withExecutePostRunScriptBeforeScraping(executePostRunScriptBeforeScraping): { spec+: { executionRequest+: { executePostRunScriptBeforeScraping: executePostRunScriptBeforeScraping } } },
      '#withExecutionLabels':: d.fn(help='"test execution labels"', args=[d.arg(name='executionLabels', type=d.T.object)]),
      withExecutionLabels(executionLabels): { spec+: { executionRequest+: { executionLabels: executionLabels } } },
      '#withExecutionLabelsMixin':: d.fn(help='"test execution labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='executionLabels', type=d.T.object)]),
      withExecutionLabelsMixin(executionLabels): { spec+: { executionRequest+: { executionLabels+: executionLabels } } },
      '#withHttpProxy':: d.fn(help='"http proxy for executor containers"', args=[d.arg(name='httpProxy', type=d.T.string)]),
      withHttpProxy(httpProxy): { spec+: { executionRequest+: { httpProxy: httpProxy } } },
      '#withHttpsProxy':: d.fn(help='"https proxy for executor containers"', args=[d.arg(name='httpsProxy', type=d.T.string)]),
      withHttpsProxy(httpsProxy): { spec+: { executionRequest+: { httpsProxy: httpsProxy } } },
      '#withImage':: d.fn(help='"container executor image"', args=[d.arg(name='image', type=d.T.string)]),
      withImage(image): { spec+: { executionRequest+: { image: image } } },
      '#withImagePullSecrets':: d.fn(help='"container executor image pull secrets"', args=[d.arg(name='imagePullSecrets', type=d.T.array)]),
      withImagePullSecrets(imagePullSecrets): { spec+: { executionRequest+: { imagePullSecrets: if std.isArray(v=imagePullSecrets) then imagePullSecrets else [imagePullSecrets] } } },
      '#withImagePullSecretsMixin':: d.fn(help='"container executor image pull secrets"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='imagePullSecrets', type=d.T.array)]),
      withImagePullSecretsMixin(imagePullSecrets): { spec+: { executionRequest+: { imagePullSecrets+: if std.isArray(v=imagePullSecrets) then imagePullSecrets else [imagePullSecrets] } } },
      '#withIsVariablesFileUploaded':: d.fn(help='', args=[d.arg(name='isVariablesFileUploaded', type=d.T.boolean)]),
      withIsVariablesFileUploaded(isVariablesFileUploaded): { spec+: { executionRequest+: { isVariablesFileUploaded: isVariablesFileUploaded } } },
      '#withJobTemplate':: d.fn(help='"job template extensions"', args=[d.arg(name='jobTemplate', type=d.T.string)]),
      withJobTemplate(jobTemplate): { spec+: { executionRequest+: { jobTemplate: jobTemplate } } },
      '#withJobTemplateReference':: d.fn(help='"name of the template resource"', args=[d.arg(name='jobTemplateReference', type=d.T.string)]),
      withJobTemplateReference(jobTemplateReference): { spec+: { executionRequest+: { jobTemplateReference: jobTemplateReference } } },
      '#withName':: d.fn(help='"test execution custom name"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { executionRequest+: { name: name } } },
      '#withNamespace':: d.fn(help='"test kubernetes namespace (\\\\\\"testkube\\\\\\" when not set)"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { executionRequest+: { namespace: namespace } } },
      '#withNegativeTest':: d.fn(help='"negative test will fail the execution if it is a success and it will succeed if it is a failure"', args=[d.arg(name='negativeTest', type=d.T.boolean)]),
      withNegativeTest(negativeTest): { spec+: { executionRequest+: { negativeTest: negativeTest } } },
      '#withNumber':: d.fn(help='"test execution number"', args=[d.arg(name='number', type=d.T.integer)]),
      withNumber(number): { spec+: { executionRequest+: { number: number } } },
      '#withPostRunScript':: d.fn(help='"script to run after test execution"', args=[d.arg(name='postRunScript', type=d.T.string)]),
      withPostRunScript(postRunScript): { spec+: { executionRequest+: { postRunScript: postRunScript } } },
      '#withPreRunScript':: d.fn(help='"script to run before test execution"', args=[d.arg(name='preRunScript', type=d.T.string)]),
      withPreRunScript(preRunScript): { spec+: { executionRequest+: { preRunScript: preRunScript } } },
      '#withPvcTemplate':: d.fn(help='"pvc template extensions"', args=[d.arg(name='pvcTemplate', type=d.T.string)]),
      withPvcTemplate(pvcTemplate): { spec+: { executionRequest+: { pvcTemplate: pvcTemplate } } },
      '#withPvcTemplateReference':: d.fn(help='"name of the template resource"', args=[d.arg(name='pvcTemplateReference', type=d.T.string)]),
      withPvcTemplateReference(pvcTemplateReference): { spec+: { executionRequest+: { pvcTemplateReference: pvcTemplateReference } } },
      '#withScraperTemplate':: d.fn(help='"scraper template extensions"', args=[d.arg(name='scraperTemplate', type=d.T.string)]),
      withScraperTemplate(scraperTemplate): { spec+: { executionRequest+: { scraperTemplate: scraperTemplate } } },
      '#withScraperTemplateReference':: d.fn(help='"name of the template resource"', args=[d.arg(name='scraperTemplateReference', type=d.T.string)]),
      withScraperTemplateReference(scraperTemplateReference): { spec+: { executionRequest+: { scraperTemplateReference: scraperTemplateReference } } },
      '#withSecretEnvs':: d.fn(help='"Execution variables passed to executor from secrets. Deprecated: use Secret Variables instead"', args=[d.arg(name='secretEnvs', type=d.T.object)]),
      withSecretEnvs(secretEnvs): { spec+: { executionRequest+: { secretEnvs: secretEnvs } } },
      '#withSecretEnvsMixin':: d.fn(help='"Execution variables passed to executor from secrets. Deprecated: use Secret Variables instead"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='secretEnvs', type=d.T.object)]),
      withSecretEnvsMixin(secretEnvs): { spec+: { executionRequest+: { secretEnvs+: secretEnvs } } },
      '#withSync':: d.fn(help='"whether to start execution sync or async"', args=[d.arg(name='sync', type=d.T.boolean)]),
      withSync(sync): { spec+: { executionRequest+: { sync: sync } } },
      '#withTestSecretUUID':: d.fn(help='"test secret uuid"', args=[d.arg(name='testSecretUUID', type=d.T.string)]),
      withTestSecretUUID(testSecretUUID): { spec+: { executionRequest+: { testSecretUUID: testSecretUUID } } },
      '#withTestSuiteName':: d.fn(help="\"unique test suite name (CRD Test suite name), if it's run as a part of test suite\"", args=[d.arg(name='testSuiteName', type=d.T.string)]),
      withTestSuiteName(testSuiteName): { spec+: { executionRequest+: { testSuiteName: testSuiteName } } },
      '#withTestSuiteSecretUUID':: d.fn(help="\"test suite secret uuid, if it's run as a part of test suite\"", args=[d.arg(name='testSuiteSecretUUID', type=d.T.string)]),
      withTestSuiteSecretUUID(testSuiteSecretUUID): { spec+: { executionRequest+: { testSuiteSecretUUID: testSuiteSecretUUID } } },
      '#withVariables':: d.fn(help='', args=[d.arg(name='variables', type=d.T.object)]),
      withVariables(variables): { spec+: { executionRequest+: { variables: variables } } },
      '#withVariablesFile':: d.fn(help='"variables file content - need to be in format for particular executor (e.g. postman envs file)"', args=[d.arg(name='variablesFile', type=d.T.string)]),
      withVariablesFile(variablesFile): { spec+: { executionRequest+: { variablesFile: variablesFile } } },
      '#withVariablesMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='variables', type=d.T.object)]),
      withVariablesMixin(variables): { spec+: { executionRequest+: { variables+: variables } } },
    },
    '#withDescription':: d.fn(help='"test description"', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withName':: d.fn(help='"test name"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { spec+: { name: name } },
    '#withSchedule':: d.fn(help='"schedule in cron job format for scheduled test execution"', args=[d.arg(name='schedule', type=d.T.string)]),
    withSchedule(schedule): { spec+: { schedule: schedule } },
    '#withSource':: d.fn(help='"reference to test source resource"', args=[d.arg(name='source', type=d.T.string)]),
    withSource(source): { spec+: { source: source } },
    '#withType':: d.fn(help='"test type"', args=[d.arg(name='type', type=d.T.string)]),
    withType(type): { spec+: { type: type } },
    '#withUploads':: d.fn(help='"files to be used from minio uploads"', args=[d.arg(name='uploads', type=d.T.array)]),
    withUploads(uploads): { spec+: { uploads: if std.isArray(v=uploads) then uploads else [uploads] } },
    '#withUploadsMixin':: d.fn(help='"files to be used from minio uploads"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='uploads', type=d.T.array)]),
    withUploadsMixin(uploads): { spec+: { uploads+: if std.isArray(v=uploads) then uploads else [uploads] } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
